name: Build Android APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Setup Capacitor
      run: |
        npm init -y
        npm install @capacitor/core@^6.2.0 @capacitor/cli@^6.2.0 @capacitor/android@^6.2.0 @capacitor/ios@^6.2.0
    
    - name: Create capacitor.config.ts
      run: |
        cat > capacitor.config.ts << EOF
        import { CapacitorConfig } from '@capacitor/cli';
        const config: CapacitorConfig = {
          appId: 'com.uberpalio.driversfriend',
          appName: 'Driver\\'s Friend',
          webDir: 'dist',
          bundledWebRuntime: false
        };
        export default config;
        EOF
    
    - name: Init Capacitor
      run: npx cap init
    
    - name: Add Android
      run: npx cap add android
    
    - name: Sync
      run: npx cap sync
    
    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: drivers-friend.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
